name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/ikunshare
        dst: gitee/ikun0014
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        src_account_type: org
        dst_account_type: user
        white_list: "Onekey"
        force_update: true
        debug: true